trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: |
        npm install
        npm test
      displayName: 'Install dependencies and run tests'
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'tiagomercuri/html21'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)

- stage: Release
  dependsOn: Build
  jobs:
  - deployment: DeployWeb
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'AzureSubscription'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Criar grupo de recursos se não existir
                az group create --name meugrupo --location eastus
                
                # Criar instância do contêiner
                az container create \
                  --resource-group meugrupo \
                  --name meucontainer \
                  --image tiagomercuri/html21:$(Build.BuildId) \
                  --dns-name-label meucontainerdns \
                  --ports 80

